version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  jobs:
    create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
    install:
      - uv sync --frozen --extra docs

mkdocs:
  configuration: mkdocs.yml
