version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  jobs:
    create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
      - uv venv
    install:
      - uv sync --frozen --extra docs
    build:
       html:
          - uv run sphinx-build -T -b html docs $READTHEDOCS_OUTPUT/html

mkdocs:
  configuration: mkdocs.yml
