site_name: AnyDI
site_description: Dependency Injection library
site_author: Anton Ruhlov
site_url: https://anydi.readthedocs.io/en/stable/

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

repo_name: python-anydi/anydi
repo_url: https://github.com/python-anydi/anydi
edit_uri: ""

nav:
  - Home: index.md
  - Getting started: getting-started.md
  - Core concepts: concepts.md
  - Usage guide:
    - Providers:
      - Overview: usage/providers/index.md
      - Basics: usage/providers/basics.md
      - Named providers: usage/providers/annotated.md
      - Resource management: usage/providers/resources.md
      - Auto-registration: usage/providers/auto-registration.md
    - Scopes: usage/scopes.md
    - Dependency injection: usage/injection.md
    - References:
      - Overview: usage/references.md
      - Global container: usage/global-container.md
    - Modules: usage/modules.md
    - Testing: usage/testing.md
    - CLI: usage/cli.md
  - Extensions:
    - FastAPI: extensions/fastapi.md
    - FastStream: extensions/faststream.md
    - Typer: extensions/typer.md
    - Pydantic settings: extensions/pydantic_settings.md
    - Django: extensions/django.md
  - Examples:
    - Basic application: examples/basic.md
    - Global container: examples/global_container.md
  - Reference: reference.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: false
            show_root_heading: true
            separate_signature: true
            members_order: source
            filters: ["!^_"]

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
